### ISSUE TITLE
changing += to +?

### ISSUE THREAD

**Issue by yayashuxue** [M3MBER-ETHDenver/M3MBER-ETHDenver#1]
I think the calculation of new expiry is wrong. On this line it should be + rather than +=

https://github.com/M3MBER-ETHDenver/M3MBER-ETHDenver/blob/de4b790fa6afd8adc88266a6c1d0d30351fa5e03/contracts/SubscriptionSubdomainRegistrar.sol#L98

**Comment by JasonFengGit** [comment]
It's fine if we do `+=` cuz the final value will be assigned to the left.
